### ISSUE TITLE
请问没有车票识别是因为sdk版本旧么

### ISSUE THREAD

**Issue by LYLSir** [qiepeipei/react-native-baidu-camera-ocr-scan#3]
我在OCR.class没有发现文档里的车票识别相关接口代码

**Comment by qiepeipei** [comment]
我们项目中没有用到这个功能所以没有做，你要是需要可以付费开发------------------ 原始邮件 ------------------
发件人: "siming,chen"<notifications@github.com>
发送时间: 2019年4月25日(星期四) 上午9:20
收件人: "qiepeipei/react-native-baidu-camera-ocr-scan"<react-native-baidu-camera-ocr-scan@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [qiepeipei/react-native-baidu-camera-ocr-scan] 请问没有车票识别是因为sdk版本旧么 (#3)



我在OCR.class没有发现文档里的车票识别相关接口代码
 
&mdash;
